#!/bin/bash

set -euo pipefail

OS_ARG=${1:?}

case "${OS_ARG}" in
    ubuntu*)
        true
        ;;

    macOS*)
        true
        ;;
esac

packages=(benchmark function2 gtest prometheus-cpp)
packages+=(boost-asio boost-callable-traits boost-chrono boost-hana boost-optional boost-mp11 boost-thread boost-variant2)

"${VCPKG_INSTALLATION_ROOT}/vcpkg" install "${packages[@]}"
