#!/bin/bash

set -euo pipefail

OS_ARG=${1:?}

BUILD_FLAGS=("--cxxopt=-std=c++14")

bazel test "${BUILD_FLAGS[@]}" --test_output=all //...

bazel run "${BUILD_FLAGS[@]}" -c opt //Test/Performance/...
